### ISSUE TITLE
Decoder_setSearch returned -1 exception

### ISSUE THREAD

**Issue by soshial** [icaksama/RapidSphinx#1]
Tried to add your code into a clean app on Huawei Honor 7. Couldn't start recognition.
Also tried you demo app and it didn't recognize any words. Returns empty string.
Maybe I didn't set up language?

**Comment by icaksama** [comment]
Yes, You need to set up the language model file first before starting the recognition. If you want to set up the language model with a file, you need set up like this: `rapidSphinx.updateLmFile(...)`

But if You want to set up language model without file You can add do that like this: `rapidSphinx.updateVocabulary(...)`. And don't forget to request the permission for recording.

**Comment by soshial** [comment]
I thought that default english LM was bundled with Sphinx. Should I add file and use it inside my APK? Or I should just use some kind of lang code like "en_US"?

**Comment by icaksama** [comment]
`I thought that default English LM was bundled with Sphinx.`
- RapidSphinx doesn't use the default English LM from Sphinx. But I will try to add it in next version.

`Should I add file and use it on my APK? I should just use some kind of lang code like "en_US"?`
- [x] Yes, if You want to use your LM file or dictionary file.
- [x] No, if You wants to use LM from String.

`Can we recognize complete strings?`
- Of course, You can add it like this:
```java
rapidSphinx.updateVocabulary("COMPLETE STRING", "DISTRACTOR STRING".split(" "), new RapidCompletionListener() {
            @Override
            public void rapidCompletedProcess() {
                //Vocabulary updated!
            }
});
```
### Make sure to remove the punctuation from your string!

**Comment by icaksama** [comment]
Hi @soshial, I just updated new version `2.1.6` with new features.
Now, you can use default English language model from Sphinx with this function:
```java
rapidSphinx.prepareRapidSphinxFullLM(new RapidPreparationListener() {
     @Override
     public void rapidPreExecute(Config config) {}

     @Override
     public void rapidPostExecute(boolean b) {}
});
```
You no need to update vocabularies again. Just call this function and start speech recognition. But, There are many vocabularies inside, so it will give you low accuracy.
